# Generated by Django 3.1.1 on 2021-08-12 11:40

import botmother.utils.api
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('type', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_action', models.CharField(max_length=255, null=True)),
                ('data', models.TextField(null=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'assistant_chats',
                'abstract': False,
            },
            bases=(models.Model, botmother.utils.api.TelegramAPI),
        ),
    ]
